### ISSUE TITLE
ECSでのみneuronがエラーする

### ISSUE THREAD

**Issue by littlemex** [littlemex/inference-samples#27]
### 背景

課題：以下のエラーでアプリが動かない。

Security Groupのアウトバウンドの設定で疎通できずにハマる->疎通したと思ったらALBの仕様上health checkがheadメソッドになっていてstatusが405になっていてハマる->neuronエラーではまる（今ここ）

- [x] ECSのImageをまずは"amazon/amazon-ecs-sample"イメージで作成して動作することを確認してOK
- [x] ALBからInstanceの該当ポート8080へのNetworkの疎通性は確認してOK
- [x] EC2（Inf1）上でのbuild、trace、inferenceは全て実施できている。 

ECSのPR: https://github.com/littlemex/inference-samples/pull/15
DockerのPR: https://github.com/littlemex/inference-samples/pull/8

```bash


INFO:     Will watch for changes in these directories: ['/app/server']
--
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using watchgod
Downloading:   0%\|          \| 0.00/252k [00:00<?, ?B/s]Downloading:   5%\|▍         \| 12.0k/252k [00:00<00:03, 76.4kB/s]Downloading:  11%\|█         \| 28.0k/252k [00:00<00:02, 89.2kB/s]Downloading:  37%\|███▋      \| 92.0k/252k [00:00<00:00, 228kB/s] Downloading:  80%\|████████  \| 202k/252k [00:00<00:00, 405kB/s] Downloading: 100%\|██████████\| 252k/252k [00:00<00:00, 387kB/s]
Downloading:   0%\|          \| 0.00/110 [00:00<?, ?B/s]Downloading: 100%\|██████████\| 110/110 [00:00<00:00, 153kB/s]
Downloading:   0%\|          \| 0.00/479 [00:00<?, ?B/s]Downloading: 100%\|██████████\| 479/479 [00:00<00:00, 711kB/s]
2022-Jun-09 12:26:15.0461     9:9     ERROR   NRT:nrt_init                                Unable to determine Neuron Driver version. Please check aws-neuron-dkms package is installed.
Process SpawnProcess-1:
Traceback (most recent call last):
File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap
self.run()
File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.7/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
target(sockets=sockets)
File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 60, in run
return asyncio.run(self.serve(sockets=sockets))
File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
return loop.run_until_complete(main)
File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
File "/usr/local/lib/python3.7/site-packages/uvicorn/server.py", line 67, in serve
config.load()
File "/usr/local/lib/python3.7/site-packages/uvicorn/config.py", line 458, in load
self.loaded_app = import_from_string(self.app)
File "/usr/local/lib/python3.7/site-packages/uvicorn/importer.py", line 21, in import_from_string
module = importlib.import_module(module_str)
File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
File "<frozen importlib._bootstrap>", line 983, in _find_and_load
File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "./main.py", line 71, in <module>
model_class = ModelInference()
File "./main.py", line 30, in __init__
self.model = torch.jit.load(model_path)
File "/usr/local/lib64/python3.7/site-packages/torch_neuron/jit_load_wrapper.py", line 13, in wrapper
script_module = jit_load(*args, **kwargs)
File "/usr/local/lib64/python3.7/site-packages/torch/jit/_serialization.py", line 162, in load
cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: The PyTorch Neuron Runtime could not be initialized. Neuron Driver issues are logged
to your system logs. See the Neuron Runtime's troubleshooting guide for help on this
topic: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/

```

**Comment by littlemex** [comment]
https://docs.amazonaws.cn/en_us/AmazonECS/latest/developerguide/ecs-inference.html#ecs-inference-requirements
公式docsを見て修正する。

**Comment by littlemex** [comment]
修正 done
